# Arquivo: .upptimerc.yml
# Fica na raiz do seu repositório no GitHub criado para o Upptime

owner: 20enzo # Mude para o seu @ do GitHub
repo: TVAberta # Ex: "monitoramento-tvaberta"

sites:
  # 1. Seu Servidor de Streaming
  - name: 🎥 Servidor de Transmissão (Vídeo)
    url: https://br5093.streamingdevideo.com.br/tvaberto/tvaberto/chunklist_w694789056.m3u8

  # 2. Seu App / Webhook
  - name: 🤖 Chatbot WhatsApp (Cloud Run)
    url: https://chatbot-whatsapp-zny5gc7sqq-uc.a.run.app/health

  # 3. Google Services (Essenciais para o bot)
  - name: 🧠 API do Google Gemini
    # Testamos a rota de descoberta global da API para saber se os servidores do Google estão de pé
    url: https://generativelanguage.googleapis.com/$discovery/rest?version=v1beta 

  - name: 📊 Google Sheets (Planilhas)
    # Testamos o servidor principal de planilhas do Google
    url: https://sheets.googleapis.com/$discovery/rest?version=v4

status-website:
  # Configurações de aparência da sua página pública
  # cname: status.fastsolutioninfo.com
  logoUrl: https://github.com/20enzo/TVAberta/public/favicon.png
  name: Status Tv Aberta
  introTitle: "**Status dos Nossos Sistemas**"
  introMessage: Acompanhe a disponibilidade dos nossos serviços em tempo real.
  theme: light

workflowSchedule:
  # Agendar verificação para rodar a cada 8 horas
  uptime: "0 */8 * * *"
